services:
  pg_guard:
    build: .
    container_name: pg_guard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pg_guard_data:/backups
    ports:
      - "3690:3690"
    restart: unless-stopped

volumes:
  pg_guard_data:
