services:
  pg_guard:
    image: ghcr.io/gilroy-digital/pg-guard:latest
    container_name: pg-guard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - pg-guard-data:/backups
    ports:
      - "3690:3690"
    restart: unless-stopped

volumes:
  pg-guard-data:
